#!/usr/bin/env zsh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
FONT_FACE="JetBrainsMono Nerd Font"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar

sketchybar	--bar \
                height=24 \
                blur_radius=0 \
                position=top \
                sticky=on \
                padding_left=0 \
                padding_right=0 \
                display=main \
                color=0xee24273a

sketchybar	--default \
                updates=when_shown \
                background.height=24 \
                background.padding_left=0 \
                background.padding_right=0 \
                background.corner_radius=0 \
                icon.color=0xff1e2030 \
                icon.font="$FONT_FACE:Bold:17.0" \
                icon.padding_left=8 \
                icon.padding_right=8 \
                label.font="$FONT_FACE:Bold:12.0" \
                label.padding_right=8 \
                label.y_offset=1 \
                label.color=0xff1e2030

sketchybar	--add	item current_space left \
            --set	current_space \
                        background.color=0xffc6a0f6 \
                        icon.font="$FONT_FACE:Bold:15.0" \
                        icon.color=0xff24273a \
                        label.drawing=off \
                        script="$PLUGIN_DIR/current_space.sh" \
            --subscribe current_space space_change mouse.clicked

sketchybar 	--add item front_app left \
            --set   front_app \
                          background.color=0xffa6da95 \
                          background.padding_left=0 \
                          background.padding_right=0 \
                          icon.y_offset=1 \
                          icon.color=0xff24273a \
                          label.drawing=no \
                          script="$PLUGIN_DIR/front_app.sh" \
          	--add item front_app.separator left \
            --set   front_app.separator \
                          icon= \
                          background.padding_left=-3 \
                          icon.font="$FONT_FACE:Bold:24.0" \
                          icon.color=0xffa6da95 \
                          icon.padding_left=0 \
                          icon.padding_right=0 \
                          label.drawing=no \
          --add item front_app.name left \
          --set front_app.name \
                    icon.drawing=off \
                    label.color=0xffcad3f5 \
                    label.padding_left=5

sketchybar  --add   bracket front_app_bracket \
                    front_app \
                    front_app.separator \
                    front_app.name \
            --subscribe	front_app front_app_switched \

sketchybar  --add   item clock right \
            --set   clock \
                        icon= \
                        icon.y_offset=1 \
                        background.color=0xffed8796 \
                        update_freq=10 \
                        script="$PLUGIN_DIR/clock.sh"

sketchybar	--add	item volume right \
            --set volume \
                width=53 \
                icon.y_offset=1 \
                background.color=0xff8aadf4 \
                script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change

sketchybar	--add	item weather.moon right \
            --set	weather.moon \
                    	background.color=0xff7dc4e4 \
                    	background.padding_right=-4 \
                    	icon.font="$FONT_FACE:Bold:22.0" \
                    	label.drawing=off \
                    	script="$PLUGIN_DIR/moon.sh" \
            --subscribe weather.moon mouse.clicked

sketchybar	--add	item weather right \
            --set	weather \
                    	icon= \
                    	icon.y_offset=1 \
                    	background.color=0xfff5bde6 \
                    	update_freq=1800 \
                    	script="$PLUGIN_DIR/weather.sh" \
            --subscribe weather system_woke

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
sketchybar	--add	item spotify_playlist right \
            --set	spotify_playlist \
                        background.color=0xffc6a0f6 \
                        icon= \
                        icon.font="$FONT_FACE:Bold:19.0" \
                        label.drawing=off \
                        script="$PLUGIN_DIR/spotify_playlist.sh" \
            --subscribe spotify_playlist mouse.clicked

sketchybar  --add   event spotify_change $SPOTIFY_EVENT \
            --add   item spotify right \
            --set   spotify \
                        icon= \
                    	icon.font="$FONT_FACE:Bold:20.0" \
                    	icon.y_offset=1 \
                        label.drawing=off \
                    	label.padding_left=2 \
                        script="$PLUGIN_DIR/spotify.sh" \
            --subscribe spotify spotify_change mouse.clicked

sketchybar	--default \
                updates=when_shown

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change volume_change spotify_change
